[package]
name = "biblizap-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-console = "0.3.0"
gloo-net = "0.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["Navigator"] }
yew = { version = "0.21.0", features = ["csr"] }
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8.5"
shuffle = "0.1.7"
js-sys = "0.3.64"
gloo-utils = "0.2.0"
csv = "1.3.0"
regex = "1.10.1"
paste = "1.0.14"
inflections = "1.1.1"
gloo-file = "0.3.0"
chrono = "0.4.31"
rust_xlsxwriter = { version = "0.61.0", features = ["wasm", "serde"] }
url = "2.5.0"
