#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME=$(basename "$0")

usage() {
	cat <<EOF
Usage: $SCRIPT_NAME --lens-api-key KEY --cache-backend-url URL [--install-dir DIR] [--binary PATH] [--service-name NAME]

Installs the biblizap-server binary and a systemd service.

Options:
	--lens-api-key KEY         (required) Lens.org API key passed to the server at runtime
	--cache-backend-url URL    (required) PostgreSQL cache database URL
	--install-dir DIR          Where to install the binary (default: /usr/bin)
	--binary PATH              Path to the built binary (default: ./target/release/biblizap-server)
	--service-name NAME        Systemd service name (default: biblizap.service)
 	--bind-address ADDR        Address to bind the server (default: 127.0.0.1)
 	--port PORT                Port to listen on (default: 35642)
	-h, --help                 Show this help
EOF
	exit 1
}

LENS_API_KEY=""
CACHE_BACKEND_URL=""
INSTALL_DIR="/usr/bin"
BINARY_PATH="./target/release/biblizap-server"
SERVICE_NAME="biblizap.service"
SERVICE_USER="biblizap"
SERVICE_GROUP="biblizap"
BIND_ADDRESS="127.0.0.1"
PORT="35642"

SYSTEMCTL_EXISTS=true
if ! command -v systemctl >/dev/null 2>&1; then
	SYSTEMCTL_EXISTS=false
fi

while [ "$#" -gt 0 ]; do
	case "$1" in
		--lens-api-key)
			LENS_API_KEY="$2"; shift 2;;
		--cache-backend-url)
			CACHE_BACKEND_URL="$2"; shift 2;;
		--install-dir)
			INSTALL_DIR="$2"; shift 2;;
		--binary)
			BINARY_PATH="$2"; shift 2;;
 		--bind-address)
 			BIND_ADDRESS="$2"; shift 2;;
	 	--port)
	 		PORT="$2"; shift 2;;
		--service-name)
			SERVICE_NAME="$2"; shift 2;;
		-h|--help)
			usage;;
		*)
			echo "Unknown arg: $1" >&2; usage;;
	esac
done

if [ -z "$LENS_API_KEY" ]; then
	echo "--lens-api-key is required" >&2
	usage
fi

if [ -z "$CACHE_BACKEND_URL" ]; then
	echo "--cache-backend-url is required" >&2
	usage
fi

if [ "$(id -u)" -ne 0 ]; then
	echo "This installer must be run as root (or via sudo)" >&2
	exit 1
fi

if [ ! -f "$BINARY_PATH" ]; then
	echo "Binary not found at '$BINARY_PATH'" >&2
	echo "Build it first with: ./build.sh --release" >&2
	exit 1
fi

mkdir -p "$INSTALL_DIR"

if [ "$SYSTEMCTL_EXISTS" = false ]; then
	echo "systemctl not found: installing binary only to $INSTALL_DIR"
	BINARY_TARGET="$INSTALL_DIR/biblizap-server"
	if [ -f "$BINARY_TARGET" ]; then
		echo "Binary already exists at $BINARY_TARGET"
		read -p "Replace it? [y/N] " -n 1 -r
		echo
		if [[ ! $REPLY =~ ^[Yy]$ ]]; then
			echo "Skipping binary installation"
			exit 0
		fi
	fi
	install -m 0755 "$BINARY_PATH" "$BINARY_TARGET"
	echo "Installed binary to $BINARY_TARGET"
	exit 0
fi

echo "Creating system user/group '$SERVICE_USER' if needed..."
if ! getent group "$SERVICE_GROUP" >/dev/null; then
	groupadd --system "$SERVICE_GROUP"
fi
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
	useradd --system --no-create-home --shell /usr/sbin/nologin --gid "$SERVICE_GROUP" "$SERVICE_USER"
fi

BINARY_TARGET="$INSTALL_DIR/biblizap-server"
if [ -f "$BINARY_TARGET" ]; then
	echo "Binary already exists at $BINARY_TARGET"
	read -p "Replace it? [y/N] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		echo "Skipping binary installation"
	else
		echo "Installing binary to $INSTALL_DIR"
		install -m 0755 "$BINARY_PATH" "$BINARY_TARGET"
	fi
else
	echo "Installing binary to $INSTALL_DIR"
	install -m 0755 "$BINARY_PATH" "$BINARY_TARGET"
fi

# Write config for the service (only when systemd is present)
CONFIG_DIR="/etc/biblizap"
CONFIG_FILE="$CONFIG_DIR/biblizap.toml"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
chown ${SERVICE_USER}:${SERVICE_GROUP} "$CONFIG_DIR"

if [ -f "$CONFIG_FILE" ]; then
	echo "Config file already exists at $CONFIG_FILE"
	read -p "Replace it? [y/N] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		echo "Keeping existing config file"
		SKIP_CONFIG=true
	else
		SKIP_CONFIG=false
	fi
else
	SKIP_CONFIG=false
fi

if [ "$SKIP_CONFIG" = false ]; then
	# create config with restrictive perms
	umask 077
	cat > "$CONFIG_FILE" <<EOF
# Biblizap configuration (generated by install.sh)
bind_address = "${BIND_ADDRESS}"
port = ${PORT}
lens_api_key = "${LENS_API_KEY}"
cache_backend_url = "${CACHE_BACKEND_URL}"
EOF
	chmod 600 "$CONFIG_FILE"
	chown ${SERVICE_USER}:${SERVICE_GROUP} "$CONFIG_FILE"
	umask 022
	echo "Wrote config to $CONFIG_FILE (mode 600, owner ${SERVICE_USER})"
fi

SERVICE_PATH="/etc/systemd/system/$SERVICE_NAME"

if [ -f "$SERVICE_PATH" ]; then
	echo "Systemd service already exists at $SERVICE_PATH"
	read -p "Replace it? [y/N] " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		echo "Keeping existing service file"
		SKIP_SERVICE=true
	else
		SKIP_SERVICE=false
	fi
else
	SKIP_SERVICE=false
fi

if [ "$SKIP_SERVICE" = false ]; then
	echo "Writing systemd unit to $SERVICE_PATH"
	cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=Biblizap Server Service
After=network.target

[Service]
Type=simple
# The server will load /etc/biblizap/biblizap.toml for bind_address, port, lens_api_key and cache_backend_url
ExecStart=$INSTALL_DIR/biblizap-server
Restart=on-failure
User=${SERVICE_USER}
Group=${SERVICE_GROUP}

[Install]
WantedBy=multi-user.target
EOF

	chmod 644 "$SERVICE_PATH"
fi

echo "Reloading systemd daemon, enabling and starting service ($SERVICE_NAME)"
systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

echo "Installation complete. Service status:"
systemctl status --no-pager "$SERVICE_NAME" || true

echo "If you need to change the Lens API key or cache URL later, edit $CONFIG_FILE and run:"
echo "  systemctl restart $SERVICE_NAME"

exit 0
